# Generated by Django 4.1.5 on 2023-01-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekdilu139', '0007_person_image_alter_person_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='sosmed',
        ),
        migrations.AddField(
            model_name='person',
            name='is_facebook',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_instagram',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_linkend',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_twitter',
            field=models.BooleanField(null=True),
        ),
    ]
