# Generated by Django 4.1.5 on 2023-01-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekdilu139', '0009_sosmed_remove_person_is_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosmed',
            name='url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
