# Generated by Django 4.1.5 on 2023-01-24 10:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekdilu139', '0011_alter_sosmed_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='pengalaman',
        ),
        migrations.AlterField(
            model_name='person',
            name='about_me',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='keahlian',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='pendidikan',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='pengalaman_kerja',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='sosmed_id',
            field=models.ManyToManyField(related_name='sosmed', to='sekdilu139.sosmed'),
        ),
    ]
