# Generated by Django 4.1.5 on 2023-01-24 11:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sekdilu139', '0012_remove_person_pengalaman_alter_person_about_me_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='keluarga',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
