# Generated by Django 4.1.5 on 2023-01-24 11:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sekdilu139', '0013_person_keluarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pilosofi',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
