# Generated by Django 4.1.5 on 2023-01-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sekdilu139', '0014_person_pilosofi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='pilosofi',
            new_name='filosofi',
        ),
    ]
